---
- name: Delete Checklist Results from remote host Playbook
  hosts: all
  become: true
  gather_facts: false

  vars:
    checklist_path: "/opt/csnap/archive"

  tasks:
    - name: "Delete Checklist Files"
      ansible.builtin.file:
        path: "{{ checklist_path }}"
        state: absent

    - name: "Debug Message"
      ansible.builtin.debug:
        msg: "Checklist files deleted successfully."
